spring:
    datasource: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testBD
      username: root
      password: 1234
      
    mvc:
      view: 
        prefix: /
        suffix: .jsp
    servlet:
      multipart:
        max-file-size: 500000kb
        max-request-size: 5000000kb 